language: node_js

node_js:
  - node

sudo: false

cache: npm

install:
  - npm ci

script:
  - npm run build

before_deploy:
  - rm -rf node_modules

deploy:
  skip_cleanup: true
  provider: heroku
  app: react-ec-shop
  api_key:
    secure: ''
