sudo: false

language: node_js

node_js:
  - 10.16.3,

cache: yarn

install:
  - yarn install

script:
  - yarn run build

  deploy:
  provider: heroku
  api_key:
    secure: "5213a6e2-1ac5-4497-abb9-961bd2c96fe3"
    app: react-ec-shop
