language: node_js
node_js:
- node
sudo: false
cache: npm
install:
- npm ci
script:
- npm run heroku-postbuild
before_deploy:
- rm -rf node_modules
deploy:
  skip_cleanup: true
  provider: heroku
  app: react-ec-shop
  api_key:
    secure: KY6hoHfrAIrSygJ2eWcqKt5xWSNAJabUb/9ztGWyo1Jzlb+HoEgM3jLOthzO2URpcXkx5UMXGA75yupQEsVp/x9dDsyhkdJZ+OAffZLiEe+ky5ZE54aBUaocMppqBDaR2yUU1INc2zl5iAmLV1iwKB2jaCRmYGX07cxorYoyhQwgZIXqViTOXtXtE0Tl/vg7XKP+GiB+pbEzS1NMo6Q0egwQT1pqsxiwow6ryGkxybekvUsSpx8sb240FQFsSvpHIuqojjTKlJy6A9Yj+5om3kg7Mho56Rc6sQXqbYqNuS1x6WyZVuxOlRbk/Vbp0Pv7jHZ8JLmdnZn07TpGdFfVMc7No/E6bONvwrKmew0cApYAfS7Seh0Aa7ZhBGU95aQz1Ykd1qY0U5XuPc1NGnmrlyQ8IzKjRDjW0GML3Epe0UPF0TOM4bj2Xl772KKkzNSwS5HAZ/UAyL7e5r4eSq5Zu4nUjL/dQ4a7SPLkNi9Gj9UjHq4++Cbh3w2CrRhfYFJ0JwWRBrU08ZxMeZvRuYDJgOaVxbyQtPYeN7K+ogcrEC2PANTMVkYHMkPDRpKKqvwKcFSN2hV7gXSCbGCyMN/RmG6HYyBcK1czncTZh5AlcSzXf9+d8Ib1Vm7TV8lzHgTcZK6wobMp+fgyZyX6Eb5ce5Y9N2NETD907obvHrCQGYw=
