# sudo: false

language: node_js

node_js:
  - 10.16.3,

before_install: # if "install" is overridden
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
cache:
  yarn: true

install:
  - yarn ci

script:
  - yarn run build

  deploy:
  provider: heroku
  api_key:
    secure: "5213a6e2-1ac5-4497-abb9-961bd2c96fe3"
    app: react-ec-shop
