language: node_js
node_js:
- node
sudo: false
cache: npm
install:
- npm ci
script:
- npm run heroku-postbuild
before_deploy:
- rm -rf node_modules
deploy:
  skip_cleanup: true
  provider: heroku
  app: react-ec-shop
  api_key:
    secure: CP3RJxT9zB4vd/o8fioY8k6WGlLQKhu8CMDuSX/Yd80/hn8DEbYswq1g6MyYwlpp6UuMa94vu1SnhAuRb5FzYMiYX/RQjrd7LvcbtixavecBBnEpkBeOASbGcmpjm7kCNrPd+hVPj7grmumyiBC1GQHdp4uPVgINz+CHvCE8IfbYcU13c7+sXFBgtyievr6aRjjrUF7WlBNzmWrrJkGRCoWswSLY5jmcvXNIyzRoL9cbKFwf2r7gBqFdCELBXxVHi/C5SD2j+/7m9pnsm8G8JS6/r3yj/n+B/VP2VwOyVfPEiViJQDZQONBicUu/B1RPURonrdkzMjZKMTdzOVMxgbSDBRS56m9zZnPtaXR/Gzhc5qT4RZ73pHMVEjYoGFHAIKbONI5Rd3yka2RdTYRrftqeNKzwnB8SNCb/UWec7TMpf9pHZvYTYCOvvYTZXqOOePO96WO2CxgKQIYtYLBtRaGDwhXTVK4PMv8bdRVv6SX0ZXscQUhGkLIU9gnMNTewZYJShyEz9WHe7qCO6cMX9TmHo56tFQV4dJkdBQsF28DkYbKsjJtAjQBjUZ3yoQQQK1bTTV+OCP/0fEXNX3Bq12Gcaw0ZT2qmdY2KEp2guhRC5MuiKxmx786KTWq4K+lS3dTDqQHWakv28hL0D1QS6Ottnas5rxVdyfoHtH1AAoI=
